import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Bell, AlertTriangle, CheckCircle2, Info, XCircle, Check, Trash2, MoreVertical } from 'lucide-react';
import { ALERTS } from '../constants';
import { cn } from '../lib/utils';
export default function AlertsList() {
    return (_jsxs("div", { className: "max-w-4xl mx-auto space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between bg-white p-4 rounded-xl border border-slate-200 shadow-sm", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "bg-[#1975d2]/10 p-2 rounded-lg text-[#1975d2]", children: _jsx(Bell, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsx("h2", { className: "font-bold text-slate-900", children: "System Notifications" }), _jsx("p", { className: "text-xs text-slate-500", children: "Manage your alerts and system messages" })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { className: "text-xs font-bold text-[#1975d2] hover:bg-[#1975d2]/5 px-3 py-1.5 rounded-lg transition-colors", children: "Mark all as read" }), _jsx("button", { className: "text-xs font-bold text-red-500 hover:bg-red-50 px-3 py-1.5 rounded-lg transition-colors", children: "Clear all" })] })] }), _jsx("div", { className: "space-y-4", children: ALERTS.map((alert) => (_jsxs("div", { className: cn("bg-white p-5 rounded-xl border transition-all hover:shadow-md flex gap-4 relative group", alert.read ? "border-slate-200 opacity-80" : "border-[#1975d2]/30 shadow-sm ring-1 ring-[#1975d2]/5"), children: [!alert.read && (_jsx("div", { className: "absolute top-5 right-5 w-2 h-2 bg-[#1975d2] rounded-full" })), _jsxs("div", { className: cn("p-3 rounded-xl shrink-0 h-fit", alert.type === 'warning' ? "bg-amber-50 text-amber-600" :
                                alert.type === 'success' ? "bg-green-50 text-green-600" :
                                    alert.type === 'error' ? "bg-red-50 text-red-600" :
                                        "bg-blue-50 text-blue-600"), children: [alert.type === 'warning' && _jsx(AlertTriangle, { className: "w-6 h-6" }), alert.type === 'success' && _jsx(CheckCircle2, { className: "w-6 h-6" }), alert.type === 'error' && _jsx(XCircle, { className: "w-6 h-6" }), alert.type === 'info' && _jsx(Info, { className: "w-6 h-6" })] }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex justify-between items-start mb-1", children: [_jsx("h3", { className: cn("font-bold text-slate-900 truncate pr-6", !alert.read && "text-[#1975d2]"), children: alert.title }), _jsx("span", { className: "text-[10px] font-bold text-slate-400 uppercase tracking-wider", children: alert.time })] }), _jsx("p", { className: "text-sm text-slate-600 leading-relaxed mb-4", children: alert.message }), _jsxs("div", { className: "flex items-center gap-3 opacity-0 group-hover:opacity-100 transition-opacity", children: [!alert.read && (_jsxs("button", { className: "flex items-center gap-1.5 text-xs font-bold text-[#1975d2] hover:underline", children: [_jsx(Check, { className: "w-3.5 h-3.5" }), "Mark as read"] })), _jsxs("button", { className: "flex items-center gap-1.5 text-xs font-bold text-red-500 hover:underline", children: [_jsx(Trash2, { className: "w-3.5 h-3.5" }), "Delete"] }), _jsxs("button", { className: "flex items-center gap-1.5 text-xs font-bold text-slate-400 hover:text-slate-600", children: [_jsx(MoreVertical, { className: "w-3.5 h-3.5" }), "Options"] })] })] })] }, alert.id))) })] }));
}
