import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Check, Edit2, Users, CreditCard, TrendingUp } from 'lucide-react';
import { MEMBERSHIP_PLANS } from '../constants';
import { cn } from '../lib/utils';
export default function MembershipPlans() {
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: [_jsx(StatCard, { icon: Users, title: "Total Members", value: "2,410", trend: "+5.4%", color: "text-[#1975d2]" }), _jsx(StatCard, { icon: CreditCard, title: "Monthly Revenue", value: "$142,500", trend: "+12.1%", color: "text-green-600" }), _jsx(StatCard, { icon: TrendingUp, title: "Churn Rate", value: "2.4%", trend: "-0.8%", color: "text-red-500" })] }), _jsx("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-8", children: MEMBERSHIP_PLANS.map((plan) => (_jsxs("div", { className: "bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col", children: [_jsxs("div", { className: cn("p-6 text-white", plan.color), children: [_jsxs("div", { className: "flex justify-between items-start mb-4", children: [_jsx("h3", { className: "text-xl font-bold", children: plan.name }), _jsx("button", { className: "p-1.5 bg-white/20 rounded-lg hover:bg-white/30 transition-colors", children: _jsx(Edit2, { className: "w-4 h-4" }) })] }), _jsxs("div", { className: "flex items-baseline gap-1", children: [_jsxs("span", { className: "text-4xl font-black", children: ["$", plan.price] }), _jsxs("span", { className: "text-sm opacity-80", children: ["/ ", plan.billing.toLowerCase()] })] })] }), _jsxs("div", { className: "p-6 flex-1 flex flex-col", children: [_jsxs("div", { className: "mb-6", children: [_jsx("p", { className: "text-xs font-bold text-slate-400 uppercase tracking-wider mb-4", children: "Plan Features" }), _jsx("ul", { className: "space-y-3", children: plan.features.map((feature, i) => (_jsxs("li", { className: "flex items-start gap-3 text-sm text-slate-600", children: [_jsx(Check, { className: "w-4 h-4 text-green-500 mt-0.5 shrink-0" }), _jsx("span", { children: feature })] }, i))) })] }), _jsxs("div", { className: "mt-auto pt-6 border-t border-slate-100", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("span", { className: "text-sm text-slate-500 font-medium", children: "Active Members" }), _jsx("span", { className: "text-sm font-bold text-slate-900", children: plan.activeMembers })] }), _jsx("div", { className: "w-full bg-slate-100 h-2 rounded-full overflow-hidden", children: _jsx("div", { className: cn("h-full rounded-full", plan.color), style: { width: `${(plan.activeMembers / 1500) * 100}%` } }) })] })] })] }, plan.id))) })] }));
}
function StatCard({ icon: Icon, title, value, trend, color }) {
    return (_jsxs("div", { className: "bg-white p-6 rounded-xl border border-slate-200 shadow-sm", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsx("div", { className: "p-3 bg-slate-50 rounded-lg text-slate-400", children: _jsx(Icon, { className: "w-5 h-5" }) }), _jsx("span", { className: cn("text-xs font-bold px-2 py-1 rounded-full", trend.startsWith('+') ? "text-green-500 bg-green-50" : "text-red-500 bg-red-50"), children: trend })] }), _jsxs("div", { className: "mt-4", children: [_jsx("p", { className: "text-sm text-slate-500 font-medium uppercase tracking-wider", children: title }), _jsx("p", { className: cn("text-2xl font-bold mt-1", color), children: value })] })] }));
}
