import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Plus, Search, Edit2, Trash2, Tag, Calendar, Users } from 'lucide-react';
import { PROMOTIONS } from '../constants';
import { cn } from '../lib/utils';
export default function PromotionsList() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex flex-col md:flex-row md:items-center justify-between gap-4", children: [_jsx("div", { className: "flex flex-wrap items-center gap-3 flex-1", children: _jsxs("div", { className: "relative w-full max-w-xs", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4" }), _jsx("input", { type: "text", placeholder: "Search promotions...", className: "w-full pl-10 pr-4 py-2 bg-white border border-slate-200 rounded-lg focus:ring-2 focus:ring-[#1975d2]/50 text-sm outline-none" })] }) }), _jsxs("button", { className: "bg-[#1975d2] hover:bg-[#1975d2]/90 text-white px-4 py-2 rounded-lg flex items-center gap-2 text-sm font-semibold transition-all", children: [_jsx(Plus, { className: "w-4 h-4" }), "Create Promotion"] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: PROMOTIONS.map((promo) => (_jsxs("div", { className: "bg-white rounded-xl border border-slate-200 shadow-sm p-6 space-y-4 relative overflow-hidden group", children: [_jsx("div", { className: cn("absolute top-0 right-0 w-2 h-full", promo.status === 'Active' ? "bg-green-500" :
                                promo.status === 'Scheduled' ? "bg-blue-500" :
                                    "bg-slate-300") }), _jsxs("div", { className: "flex justify-between items-start", children: [_jsx("div", { className: "bg-slate-50 p-3 rounded-lg text-[#1975d2]", children: _jsx(Tag, { className: "w-6 h-6" }) }), _jsxs("div", { className: "flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity", children: [_jsx("button", { className: "p-1.5 text-slate-400 hover:text-[#1975d2] transition-colors", children: _jsx(Edit2, { className: "w-4 h-4" }) }), _jsx("button", { className: "p-1.5 text-slate-400 hover:text-red-500 transition-colors", children: _jsx(Trash2, { className: "w-4 h-4" }) })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-bold text-slate-900", children: promo.name }), _jsx("p", { className: "text-sm font-mono font-bold text-[#1975d2] mt-1", children: promo.code })] }), _jsx("div", { className: "flex items-center gap-2 text-2xl font-black text-slate-900", children: promo.discount }), _jsxs("div", { className: "space-y-2 pt-2", children: [_jsxs("div", { className: "flex items-center gap-2 text-xs text-slate-500 font-medium", children: [_jsx(Calendar, { className: "w-3.5 h-3.5" }), _jsxs("span", { children: [promo.startDate, " - ", promo.endDate] })] }), _jsxs("div", { className: "flex items-center gap-2 text-xs text-slate-500 font-medium", children: [_jsx(Users, { className: "w-3.5 h-3.5" }), _jsxs("span", { children: [promo.usage, " redemptions"] })] })] }), _jsxs("div", { className: "pt-4 border-t border-slate-100 flex items-center justify-between", children: [_jsx("span", { className: cn("px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider", promo.status === 'Active' ? "bg-green-50 text-green-600" :
                                        promo.status === 'Scheduled' ? "bg-blue-50 text-blue-600" :
                                            "bg-slate-100 text-slate-500"), children: promo.status }), _jsx("button", { className: "text-xs font-bold text-[#1975d2] hover:underline", children: "View Analytics" })] })] }, promo.id))) })] }));
}
