import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FileText, Download, Search, Calendar, FileSpreadsheet, FileJson, MoreVertical } from 'lucide-react';
import { REPORTS } from '../constants';
import { cn } from '../lib/utils';
export default function ReportsList() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex flex-col md:flex-row md:items-center justify-between gap-4", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-3 flex-1", children: [_jsxs("div", { className: "relative w-full max-w-xs", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4" }), _jsx("input", { type: "text", placeholder: "Search reports...", className: "w-full pl-10 pr-4 py-2 bg-white border border-slate-200 rounded-lg focus:ring-2 focus:ring-[#1975d2]/50 text-sm outline-none" })] }), _jsxs("select", { className: "bg-white border border-slate-200 rounded-lg px-3 py-2 text-sm text-slate-600 focus:ring-[#1975d2] outline-none", children: [_jsx("option", { children: "All Categories" }), _jsx("option", { children: "Financial" }), _jsx("option", { children: "Inventory" }), _jsx("option", { children: "Staff" }), _jsx("option", { children: "Customers" })] })] }), _jsxs("button", { className: "bg-[#1975d2] hover:bg-[#1975d2]/90 text-white px-4 py-2 rounded-lg flex items-center gap-2 text-sm font-semibold transition-all", children: [_jsx(FileText, { className: "w-4 h-4" }), "Generate New Report"] })] }), _jsx("div", { className: "bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden", children: _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left border-collapse", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-slate-100 bg-slate-50/50", children: [_jsx("th", { className: "px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider", children: "Report Name" }), _jsx("th", { className: "px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider", children: "Category" }), _jsx("th", { className: "px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider", children: "Date Generated" }), _jsx("th", { className: "px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider", children: "Format" }), _jsx("th", { className: "px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider", children: "Size" }), _jsx("th", { className: "px-6 py-4 text-xs font-bold text-slate-500 uppercase tracking-wider text-right", children: "Actions" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-100", children: REPORTS.map((report) => (_jsxs("tr", { className: "hover:bg-slate-50/80 transition-colors group", children: [_jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: cn("p-2 rounded-lg", report.format === 'PDF' ? "bg-red-50 text-red-500" :
                                                            report.format === 'XLS' ? "bg-green-50 text-green-500" :
                                                                "bg-blue-50 text-blue-500"), children: [report.format === 'PDF' && _jsx(FileText, { className: "w-5 h-5" }), report.format === 'XLS' && _jsx(FileSpreadsheet, { className: "w-5 h-5" }), report.format === 'CSV' && _jsx(FileJson, { className: "w-5 h-5" })] }), _jsx("span", { className: "text-sm font-bold text-slate-900 group-hover:text-[#1975d2] transition-colors", children: report.title })] }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsx("span", { className: "px-2.5 py-1 text-[10px] font-bold rounded-full bg-slate-100 text-slate-600 uppercase", children: report.category }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-slate-500", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Calendar, { className: "w-3.5 h-3.5" }), report.date] }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm font-bold text-slate-700", children: report.format }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-slate-400 font-medium", children: report.size }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-right", children: _jsxs("div", { className: "flex justify-end gap-2", children: [_jsxs("button", { className: "flex items-center gap-2 px-3 py-1.5 bg-[#1975d2] text-white text-xs font-bold rounded-lg hover:bg-[#1975d2]/90 transition-all", children: [_jsx(Download, { className: "w-3.5 h-3.5" }), "Download"] }), _jsx("button", { className: "p-1.5 text-slate-400 hover:text-slate-600 transition-colors", children: _jsx(MoreVertical, { className: "w-4 h-4" }) })] }) })] }, report.id))) })] }) }) })] }));
}
